name: optimize resource pack
on: push
permissions: 
  actions: read
  contents: write
jobs:
  packsquash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: latest
          options: |
            pack_directory = '.'
            output_file_path = 'GameOfLife.zip'
            recompress_compressed_files = true
            zip_compression_iterations = 30
            zip_spec_conformance_level = 'disregard'
            ['**/*?.{json,jem,jpm,mcmeta,bbmodel}']
            always_allow_json_comments = false
            ['**/*?.png']
            image_data_compression_iterations = 15
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: GameOfLife.zip